oceanicshadow88/luma-ai-be

- .env.example
- .gitignore
- package.json
- src/config/index.ts
- src/controllers/authController.ts
- src/handlers/v1/authRoute.ts
- src/handlers/v1/index.ts
- src/lib/jwtUtils.ts
- src/middleware/auth.ts
- src/models/user.ts
- src/services/userService.ts
- tests/unit/userService.test.ts
- yarn.lock
- Add JWT function
- add test jwt api
- modify related api for jwt added
> feat: add JWT function

- src/controllers/authController.ts
- src/handlers/v1/authRoute.ts
- src/validations/userAuthValidation.ts
fix:refreshtoken joi validation
> fix:refreshtoken joi validation

- src/controllers/companyController.ts
- src/middleware/rateLimit.ts
- src/models/company.ts
- src/services/companyService.ts
- src/validations/companyValidaton.ts
- src/validations/userAuthValidation.ts
fix: edit data validation according frontend required
> fix: edit joi validation according frontend required

- src/controllers/invitationController.ts
- src/services/invitationService.ts
- src/types/invitation.ts
- src/validations/userAuthValidation.ts
> LA-64: add user in invite api

- src/controllers/auth/registerController.ts
- src/handlers/v1/api.ts
- src/middleware/saasMiddleware.ts
> LA-65: Saas middlware

- src/services/auth/registerService.ts
LA-67: TEMP: Remove checkVerificationCode in createUserAndTokens avoid registerion error
> LA-67: TEMP: Remove checkVerificationCode in createUserAndTokens avoid registerion error

- src/middleware/validation/adminRegistrationPreCheck.ts
- src/models/user.ts
- src/services/auth/registerService.ts
- src/services/membershipService.ts
Verify if username and email are duplicated when registering input data in admin.
Change create membership function name to avoid misunderstanding
> bugfix / LA-21 admin register check username and email

- README.md
- docker-compose.yml
- src/middleware/morgan.ts
change NODE_ENV value to local.
change Readme file .env.development to .env
change morgan  NODE_ENV value to local to make sure logger function
> [bugfix]: LUM-8 .env NODE_ENV=local not development

- src/lib/jwtUtils.ts
- src/middleware/authGuard.ts
- src/models/user.ts
##change
1. remove chinese comments
2. fix user to userId make sure the consistent variable references in different files for token generate
> [bugfix]: lum-16 token error - user and userId confuse

- src/controllers/adminDashboardController.ts
- src/controllers/dashboardController.ts
- src/services/userService.ts
##backgroud
One user may belong multiple companies.
##Change
1. According userId and companyId get unique membership.
2. get current user info in dashboard controller.
> [feature] LUM-3-4 get current user info from membership service

- src/models/user.ts
- src/services/auth/registerService.ts
- src/services/invitationService.ts
This pull request updates the `registerService` in the `src/services/auth` module to enhance password security by hashing passwords before updating user records. The most important changes include adding the `bcryptjs` library and modifying the `findOneAndUpdate` logic to hash passwords.
* [`src/services/auth/registerService.ts`](diffhunk://#diff-649fc21955cdeba571edea310b2971cbd51ea801efd188448debb43520dd436aR2): Imported `bcryptjs` to handle password hashing.
* [`src/services/auth/registerService.ts`](diffhunk://#diff-649fc21955cdeba571edea310b2971cbd51ea801efd188448debb43520dd436aL35-R43): Updated the `registerService` logic to hash the user's password using `bcrypt.hash` before updating the user record in the database.
> LUM 17 - teacher sign up hash password

- src/database/seeder/companySeeder.ts
- src/database/seeder/userSeeder.ts
- src/middleware/validation/teacherRegistrationPreCheck.ts
- src/types/express/index.d.ts
change type avoid eslint warning for any type
> [bugfix] LUM-15 fix type avoid eslint error for any type

- src/handlers/v1/api.ts
- src/middleware/validation/adminRegistrationPreCheck.ts
- src/middleware/validation/teacherRegistrationPreCheck.ts
1. Change name to distinguish between admin and teacher pre check.
2. Add verification code verification.
3. Change get company slug from subdomain not from email.(Teacher not require work email)
> [Bugfix]: LUM-23 Teacher registration pre check

- src/controllers/auth/registerController.ts
- src/services/auth/registerService.ts
After the teacher registers, there is no return information. If auto jump directly to the dashboard, there is a lack of token.
1. Generate two token after teacher registered successfully in teacher register service
2. Return token in teacher register controller.
> [Feature]: Add return token after teacher registed success

- src/controllers/auth/registerController.ts
Fix error:  Cannot set headers after they are sent to the client
change res.sendStatus to res.status in registerController
> [Bugfix]: LUM-21 change res.sendStatus to res.status

- src/services/auth/loginService.ts
1. Standardize the format of error messages.
2. Change the error message status code that does not need to be exposed to users to 500.
3. A prompt must be given to users to use payload to record specific details in the logger that only developers can see.
> [Bugfix]: LA-86 change login error message

- src/middleware/saasMiddleware.ts
1. Standardize the format of error messages
2. Change the error message status code that does not need to be exposed to users to 500
3. Information that must be returned to the user, using payload to record specific details in the logger that only developers can see
> [Bugfix]: LA-86 fix sass error messsage

- .husky/pre-commit
- README.md
- jest.config.ts
- nodemon.json
- package.json
- tsconfig.json
- tsconfig.test.json
- yarn.lock
Added test folder, but configuration does not match.
1. Change tests to test.
2. Add absolute path for test.
3. Modify other configurations to match the current functionality.
4. jest.config.js change to jest.config.ts
5. Update dependences
> 【Chore】: LA-99 update configuration to adapt

- src/controllers/auth/passwordResetController.ts
- src/middleware/saasMiddleware.ts
- src/middleware/validation/adminRegistrationPreCheck.ts
- src/services/auth/loginService.ts
- src/services/auth/registerService.ts
404 error code only applies to pages that cannot be found. Changing all models cannot be found in the database error code.
1. Change local model model not exist error code to 500.
2. Change other model model not exist but need return to frontend to 401.
> 【Bugfix】: LA-86 fix 404 error code

- src/lib/jwtUtils.ts
- src/middleware/error/errorHandler.ts
- src/services/auth/authService.ts
- src/utils/invitationLink.ts
1. Add field for token error message.
> 【Bugfix】: LA-102 token error message

- src/controllers/auth/passwordResetController.ts
- src/services/auth/registerService.ts
- test/__test__/resetPassword.test.ts
- test/__test__/signUpLearner.test.ts
1. Change error message, code change to verify value.
> [Bugfix]: LA-97 error message code change to verifyValue

- src/validations/userAuthValidation.ts
username only letters and numbers
> [Bugfix]: LA-111 username only letters and numbers

- src/services/auth/registerService.ts
1. Allow student signup in different company with same email.
2. Allow student Signup with or without invitation link.
> [Feature]: LA-120 allow student signup with or without invitation link

- src/controllers/auth/logoutController.ts
- src/services/auth/logoutService.ts
1. Throw 500 error if no refreshToken.
> [Feature]: LA-124 Logout

- src/controllers/dashboardController.ts
- src/handlers/v1/api.ts
- src/middleware/someAuth.ts
- src/services/userService.ts
rename-someAuth
relove-error-warning
> chore: la-132 LA-132-rename-someAuth-relove-error-warning

- src/controllers/auth/registerController.ts
- src/handlers/v1/api.ts
- src/services/auth/registerService.ts
- test/__test__/builders/userBuilder.ts
- test/__test__/signUpCompany.test.ts
- test/setup/jest-setup.ts
1. Split company signup according controller and service level.
2. Refactor user builder for test case: add role and company field.
3. Refactor defaultUser initial add new field.
4. Add test case.
5. Remove unused TODO comments.
> [Bugfix]LA-105 company signup refactor

- src/controllers/auth/verifyCodeController.ts
- src/services/verificationService.ts
- test/__test__/verificationCode.test.ts
1. split request verification code controller and service.
2. Test case
> [Bugfix]LA-136 split request verification code

- src/config/constants.ts
- src/config/index.ts
- src/controllers/auth/registerController.ts
- src/database/seeder/companySeeder.ts
- src/middleware/authGuard.ts
- src/middleware/validateTokenAndUrlWithInvitedUser.ts
- src/models/company.ts
- src/models/user.ts
- src/services/auth/loginService.ts
- src/services/auth/registerService.ts
- src/services/companyService.ts
- src/services/companyUsageService.ts
- src/services/invitationService.ts
- src/services/userService.ts
- src/types/constantsTypes.ts
- src/types/invitation.ts
- src/utils/invitationLink.ts
- src/validations/companyValidation.ts
- src/validations/invitationValidation.ts
- src/validations/userAuthValidation.ts
- test/__test__/builders/companyBuilder.ts
- test/__test__/builders/userBuilder.ts
- test/__test__/signUpCompany.test.ts
- test/setup/jest-setup.ts
##Change
Separate types into an index file.
Update related imports accordingly.
Change to use roleList in validateTokenAndUrlWithInvitedUser.
> [Bugfix]LA-134 split constant types
